### ISSUE TITLE
rejection error: relation "____" does not exist - Probably a simple case-sensitive issue

### ISSUE THREAD

**Issue by arnaudDerbey** [prostgles/prostgles-server-js#2]
Whenever i try to subscribe on a table I get the following error: 
**rejection error: relation _"tableName"_ does not exist**. 

My table name are written with an uppercase first letter like so : **Events**. But the error return the table name in lowercase => **events** . 

It sounds like a simple case-sensitive issue. 

Anyway you did a great lib and probably deserve more upvote on PH !

**Comment by prostgles** [comment]
I appreciate your support!
I have just fixed this issue in v1.0.33

Let me know if you run into other issues

Many thanks!

**Comment by arnaudDerbey** [comment]
Works like a charm ! Thank you !
